const fs = require('fs');
const path = require('path');

// --- Configuration ---
const rootDir = path.join(__dirname, '..');

// Colors
const colors = {
    cyan: "\x1b[36m",
    green: "\x1b[32m",
    yellow: "\x1b[33m",
    red: "\x1b[31m",
    gray: "\x1b[90m",
    reset: "\x1b[0m",
};

// Arguments
const args = process.argv.slice(2);
const cleanDeps = args.includes('--deps');

// Paths to clean (Standard Build Artifacts)
const artifacts = [
    { path: 'dist', type: 'dir' },
    { path: 'release', type: 'dir' },
    { path: '.tmp', type: 'dir' },
    { path: 'neutralinojs.log', type: 'file' },
    { path: 'Stable_Studio_Setup.exe', type: 'file' },

    // CSS & JS Assets
    { path: 'resources/css/styles.css', type: 'file' },
    { path: 'resources/css/daisyui.css', type: 'file' },
    { path: 'resources/css/tailwindcss.js', type: 'file' },

    // Neutralino Client Libs (Regenerated by neu update)
    { path: 'resources/js/neutralino.js', type: 'file' },
    { path: 'resources/js/neutralino.d.ts', type: 'file' }
];

// Paths to clean if --deps flag is used
const dependencyArtifacts = [
    { path: 'node_modules', type: 'dir' },
    { path: 'bin', type: 'dir' }
];

function log(emoji, message) {
    console.log(`${emoji}  ${message}`);
}

function removePath(relativePath) {
    const fullPath = path.join(rootDir, relativePath);

    if (fs.existsSync(fullPath)) {
        try {
            fs.rmSync(fullPath, { recursive: true, force: true });
            console.log(`   ${colors.red}deleted:${colors.reset} ${relativePath}`);
        } catch (e) {
            console.log(`   ${colors.yellow}failed:${colors.reset} ${relativePath} - ${e.message}`);
        }
    }
}

function cleanDirectoryContents(relativePath, keepExtensions = []) {
    const dirPath = path.join(rootDir, relativePath);
    if (!fs.existsSync(dirPath)) return;

    const files = fs.readdirSync(dirPath);
    let count = 0;

    files.forEach(file => {
        if (file === '.gitkeep') return;
        if (keepExtensions.some(ext => file.endsWith(ext))) return;

        const fullPath = path.join(dirPath, file);
        try {
            fs.rmSync(fullPath, { recursive: true, force: true });
            count++;
        } catch (e) { }
    });

    if (count > 0) {
        console.log(`   ${colors.red}cleaned:${colors.reset} ${relativePath} (${count} files removed)`);
    }
}

// --- Main Execution ---

console.log(colors.cyan + "==================================================" + colors.reset);
console.log(colors.cyan + "            Project Cleanup Utility               " + colors.reset);
console.log(colors.cyan + "==================================================" + colors.reset);

// 1. Clean Build Artifacts
log("🧹", "Cleaning build artifacts...");
artifacts.forEach(item => removePath(item.path));

// 2. Clean Temp Files
log("🗑️", "Cleaning temp directories...");
cleanDirectoryContents('temp');

// 3. Clean Dependencies (If flag provided)
if (cleanDeps) {
    log("📦", "Cleaning dependencies (--deps)...");
    dependencyArtifacts.forEach(item => removePath(item.path));
    console.log(`   ${colors.yellow}Note: You will need to run 'npm run init' again.${colors.reset}`);
}

console.log(colors.green + "\n✔ Cleanup complete." + colors.reset);